/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Diammond.J' at '16-11-24 下午2:19' with Gradle 2.11
 *
 * @author Diammond.J, @date 16-11-24 下午2:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
